apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: localhost:5000/distinction
          ports:
          - containerPort: 8080
          env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgres-service:5432/mydatabase
          - name: SPRING_DATASOURCE_USERNAME
            value: postgres
          - name: SPRING_DATASOURCE_PASSWORD
            value: "1234"
